#!/usr/bin/env bash
#
# Run unit tests and create report
#
# TESTFLAGS - add additional test flags. Ex:
#
#   TESTFLAGS='-v -run TestBuild' hack/test/unit
#
# TESTDIRS - run tests for specified packages. Ex:
#
#   TESTDIRS='./pkg/term' hack/test/unit
#
set -eux -o pipefail

ABS_BUILDDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/../../build"
export PATH="$ABS_BUILDDIR/binary:$PATH"

BUILDFLAGS=(-tags 'netgo seccomp libdm_no_deferred_remove')
TESTFLAGS+=" -test.timeout=${TIMEOUT:-5m}"
TESTDIRS="${TESTDIRS:-./...}"
exclude_paths='/vendor/|/integration'
pkg_list=$(go list $TESTDIRS | grep -vE "($exclude_paths)")

base_pkg_list=$(echo "${pkg_list}" | grep --fixed-strings -v "/libnetwork" || :)
libnetwork_pkg_list=$(echo "${pkg_list}" | grep --fixed-strings "/libnetwork" || :)

mkdir -p build

if [ -n "${base_pkg_list}" ]; then
	gotestsum --format=standard-quiet --jsonfile=build/go-test-report.json --junitfile=build/junit-report.xml -- \
		"${BUILDFLAGS[@]}" \
		-cover \
		-coverprofile=build/profile.out \
		-covermode=atomic \
		${TESTFLAGS} \
		${base_pkg_list}
fi
if [ -n "${libnetwork_pkg_list}" ]; then
	# libnetwork tests invoke iptables, and cannot be run in parallel. Execute
	# tests within /libnetwork with '-p=1' to run them sequentially. See
	# https://github.com/moby/moby/issues/42458#issuecomment-873216754 for details.
	gotestsum --format=standard-quiet --jsonfile=build/go-test-report-libnetwork.json --junitfile=build/junit-report-libnetwork.xml -- \
		"${BUILDFLAGS[@]}" \
		-cover \
		-coverprofile=build/profile-libnetwork.out \
		-covermode=atomic \
		-p=1 \
		${TESTFLAGS} \
		${libnetwork_pkg_list}
fi
