#!/usr/bin/env bash
set -e

[ -z "$KEEPDEST" ] && rm -rf "$DEST"

(
	if [ -n "$DEST" ]; then
		OUTPUT="$(dirname "$DEST")/binary"
		export OUTPUT
	fi
	if [ "$(go env GOOS)" = "linux" ]; then
		export GO_LDFLAGS="-linkmode=external"
	fi
	export PACKAGE=./cmd/docker-proxy
	. hack/make/.binary
)
