#!/usr/bin/env bash
set -e

[ -z "$KEEPDEST" ] && rm -rf "$DEST"

(
	if [ -n "$DEST" ]; then
		OUTPUT="$(dirname "$DEST")/dynbinary"
		export OUTPUT
	fi
	export GO_LINKMODE="dynamic"
	export PACKAGE=./cmd/dockerd
	. hack/make/.binary
)
