name: ci

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
      - '[0-9]+.[0-9]{2}'
    tags:
      - 'v*'
  pull_request:

env:
  PLATFORM: "Docker Engine - Community"
  PRODUCT: "Moby"
  DEFAULT_PRODUCT_LICENSE: "Community Engine"
  PACKAGER_NAME: "Docker, Inc."

jobs:
  binary:
    runs-on: ubuntu-20.04
    env:
      BINARY_OUTPUT: ./build
    strategy:
      fail-fast: false
      matrix:
        linkmode:
          - static
          - dynamic
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build
        uses: docker/bake-action@v1
        with:
          targets: binary
          set: |
            *.cache-from=type=gha,scope=build-${{ matrix.linkmode }}
            *.cache-to=type=gha,scope=build-${{ matrix.linkmode }}
        env:
          GO_LINKMODE: ${{ matrix.linkmode }}
      -
        name: List artifacts
        run: |
          tree -nh ${{ env.BINARY_OUTPUT }}
      -
        name: Check artifacts
        run: |
          find ${{ env.BINARY_OUTPUT }} -type f -exec file -e ascii -- {} +
      -
        name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: binary-${{ matrix.linkmode }}
          path: ${{ env.BINARY_OUTPUT }}
          if-no-files-found: error
          retention-days: 7

  cross:
    runs-on: ubuntu-20.04
    env:
      BUNDLE_OUTPUT: ./build
    strategy:
      fail-fast: false
      matrix:
        target:
          - bundle
        platform:
          - linux/amd64
          - linux/arm/v5
          - linux/arm/v6
          - linux/arm/v7
          - linux/arm64
          - linux/ppc64le
          - linux/riscv64
          - linux/s390x
          - windows/amd64
          - windows/arm64
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Prepare
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build
        uses: docker/bake-action@v1
        with:
          targets: ${{ matrix.target }}
          set: |
            *.platform=${{ matrix.platform }}
            *.cache-from=type=gha,scope=cross-${{ matrix.target }}-${{ env.PLATFORM_PAIR }}
            *.cache-to=type=gha,scope=cross-${{ matrix.target }}-${{ env.PLATFORM_PAIR }}
      -
        name: List artifacts
        run: |
          tree -nh ${{ env.BUNDLE_OUTPUT }}
      -
        name: Check artifacts
        run: |
          find ${{ env.BUNDLE_OUTPUT }} -type f -exec file -e ascii -- {} +
      -
        name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: cross-${{ matrix.target }}-${{ env.PLATFORM_PAIR }}
          path: ${{ env.BUNDLE_OUTPUT }}
          if-no-files-found: error
          retention-days: 7

  test-buildkit:
    needs:
      - binary
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        pkg:
          - ./client
          - ./cmd/buildctl
          - ./solver
          - ./frontend
          - ./frontend/dockerfile
        typ:
          - integration
        include:
          - pkg: ./...
            skip-integration-tests: 1
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          path: moby
      -
        name: BuildKit ref
        run: |
          ./hack/go-mod-prepare.sh
          echo "BUILDKIT_REF=$(./hack/buildkit-ref)" >> $GITHUB_ENV
        working-directory: moby
      -
        name: Checkout BuildKit ${{ env.BUILDKIT_REF }}
        uses: actions/checkout@v3
        with:
          repository: "moby/buildkit"
          ref: ${{ env.BUILDKIT_REF }}
          path: buildkit
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Download binary artifacts
        uses: actions/download-artifact@v3
        with:
          name: binary-static
          path: ./buildkit/build/moby/
      -
        name: Update daemon.json
        run: |
          sudo rm /etc/docker/daemon.json
          sudo service docker restart
          docker version
          docker info
      -
        name: Test
        run: |
          ./hack/test ${{ matrix.typ }}
        env:
          CONTEXT: "."
          TEST_DOCKERD: "1"
          TEST_DOCKERD_BINARY: "./build/moby/dockerd"
          TESTPKGS: "${{ matrix.pkg }}"
          TESTFLAGS: "-v --parallel=1 --timeout=30m --run=//worker=dockerd$"
          SKIP_INTEGRATION_TESTS: "${{ matrix.skip-integration-tests }}"
        working-directory: buildkit

  dev:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        mode:
          - ""
          - systemd
    steps:
      -
        name: Prepare
        run: |
          if [ "${{ matrix.mode }}" = "systemd" ]; then
            echo "DEV_SYSTEMD=true" >> $GITHUB_ENV
          fi
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build dev image
        uses: docker/bake-action@v1
        with:
          targets: dev
          set: |
            dev.cache-from=type=gha,scope=dev${{ matrix.mode }}
            dev.cache-to=type=gha,scope=dev${{ matrix.mode }},mode=max
            dev.output=type=cacheonly
